// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/templui/templui/components/button"
	"github.com/templui/templui/components/icon"
)

type ThemeSwitcherProps struct {
	Class string
}

func ThemeSwitcher(props ...ThemeSwitcherProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var p ThemeSwitcherProps
		if len(props) > 0 {
			p = props[0]
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script nonce=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.GetNonce(ctx))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/themeswitcher.templ`, Line: 17, Col: 36}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">\n\t\t(function() {\n\t\t\tfunction getThemePreference() {\n\t\t\t\treturn localStorage.getItem('themePreference') || 'system';\n\t\t\t}\n\n\t\t\tfunction applyTheme() {\n\t\t\t\tconst preference = getThemePreference();\n\t\t\t\tlet isDark = false;\n\n\t\t\t\tif (preference === 'system') {\n\t\t\t\t\tisDark = window.matchMedia('(prefers-color-scheme: dark)').matches;\n\t\t\t\t} else {\n\t\t\t\t\tisDark = preference === 'dark';\n\t\t\t\t}\n\n\t\t\t\tdocument.documentElement.classList.toggle('dark', isDark);\n\t\t\t\tdocument.dispatchEvent(new CustomEvent('theme-changed'));\n\t\t\t}\n\n\t\t\tfunction cycleTheme() {\n\t\t\t\tconst current = getThemePreference();\n\t\t\t\tlet next;\n\n\t\t\t\tif (current === 'system') {\n\t\t\t\t\tconst isDarkNow = window.matchMedia('(prefers-color-scheme: dark)').matches;\n\t\t\t\t\tnext = isDarkNow ? 'light' : 'dark';\n\t\t\t\t} else {\n\t\t\t\t\tnext = current === 'light' ? 'dark' : 'light';\n\t\t\t\t}\n\n\t\t\t\tlocalStorage.setItem('themePreference', next);\n\t\t\t\tapplyTheme();\n\t\t\t}\n\n\t\t\tapplyTheme();\n\n\t\t\twindow.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', () => {\n\t\t\t\tif (getThemePreference() === 'system') {\n\t\t\t\t\tapplyTheme();\n\t\t\t\t}\n\t\t\t});\n\n\t\t\tdocument.addEventListener('click', (e) => {\n\t\t\t\tconst themeSwitcher = e.target.closest('[data-theme-switcher]');\n\t\t\t\tif (themeSwitcher) {\n\t\t\t\t\te.preventDefault();\n\t\t\t\t\tcycleTheme();\n\t\t\t\t}\n\t\t\t});\n\t\t})();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = icon.Eclipse(icon.Props{Class: "size-5"}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = button.Button(button.Props{
			Size:    button.SizeIcon,
			Variant: button.VariantGhost,
			Class:   p.Class,
			Attributes: templ.Attributes{
				"data-theme-switcher": "true",
			},
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
