stages:
  - build

variables:
  OUTPUT_DIR: 'bin'
  GOFLAGS: '-mod=mod'

build_linux:
  stage: build
  image: golang:latest
  script:
    - mkdir -p $OUTPUT_DIR
    - GOOS=linux GOARCH=amd64 go build -o $OUTPUT_DIR/regius-linux
  artifacts:
    paths:
      - $OUTPUT_DIR/regius-linux
  only:
    - /^v1.\d+.\d+$/

build_windows:
  stage: build
  image: golang:latest
  script:
    - mkdir -p $OUTPUT_DIR
    - GOOS=windows GOARCH=amd64 go build -o $OUTPUT_DIR/regius-windows.exe
  artifacts:
    paths:
      - $OUTPUT_DIR/regius-windows.exe
  only:
    - /^v1.\d+.\d+$/

build_mac:
  stage: build
  image: golang:latest
  script:
    - mkdir -p $OUTPUT_DIR
    - GOOS=darwin GOARCH=amd64 go build -o $OUTPUT_DIR/regius-mac
  artifacts:
    paths:
      - $OUTPUT_DIR/regius-mac
  only:
    - /^v1.\d+.\d+$/
