CREATE TABLE IF NOT EXISTS $TABLE_NAME (
    id INT AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

-- TODO: add columns for the $TABLE_NAME table, e.g.:
-- ALTER TABLE $TABLE_NAME ADD COLUMN title VARCHAR(255) NOT NULL DEFAULT '';
-- ALTER TABLE $TABLE_NAME ADD COLUMN body TEXT NOT NULL;
