CREATE TABLE IF NOT EXISTS $TABLE_NAME (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- TODO: add columns for the $TABLE_NAME table, e.g.:
-- ALTER TABLE $TABLE_NAME ADD COLUMN title TEXT NOT NULL DEFAULT '';
-- ALTER TABLE $TABLE_NAME ADD COLUMN body TEXT NOT NULL DEFAULT '';
