CREATE TABLE IF NOT EXISTS $TABLE_NAME (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- TODO: add columns for the $TABLE_NAME table, e.g.:
-- ALTER TABLE $TABLE_NAME ADD COLUMN title TEXT NOT NULL DEFAULT '';
-- ALTER TABLE $TABLE_NAME ADD COLUMN body TEXT NOT NULL DEFAULT '';
