package main

import (
	"embed"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
)

//go:embed templates
var templateFS embed.FS

//go:embed all:_skeleton
var skeletonFS embed.FS

// writeSkeleton writes the embedded skeleton app tree into targetDir.
// It skips go.mod (written from templates/go_mod) and go.sum (regenerated by go mod tidy).
func writeSkeleton(targetDir string) error {
	root, err := fs.Sub(skeletonFS, "_skeleton")
	if err != nil {
		return err
	}

	return fs.WalkDir(root, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if path == "go.mod" || path == "go.sum" {
			return nil
		}

		data, rerr := fs.ReadFile(root, path)
		if rerr != nil {
			return rerr
		}

		return copyDataToFile(data, filepath.Join(targetDir, path))
	})
}

func copyFileFromTemplate(templatePath, targetFile string) error {
	if fileExists(targetFile) {
		fmt.Println("File already exists:", targetFile)
		return nil
	}

	data, err := templateFS.ReadFile(templatePath)
	if err != nil {
		exitGracefully(err)
	}

	err = copyDataToFile(data, targetFile)
	if err != nil {
		exitGracefully(err)
	}

	return nil
}

func copyDataToFile(data []byte, to string) error {
	err := os.MkdirAll(filepath.Dir(to), 0755)
	if err != nil {
		return err
	}
	err = os.WriteFile(to, data, 0644)
	if err != nil {
		return err
	}

	return nil
}

func fileExists(fileToCheck string) bool {
	if _, err := os.Stat(fileToCheck); os.IsNotExist(err) {
		return false
	}

	return true
}
